/* A real-time 3D globe: spherical terrain mesh, raised forests and city geometry. */
(()=>{
const $=id=>document.getElementById(id),DURATION=64,TAU=Math.PI*2;
let running=false,raf=0,ac=null,source=null,rec=null,stream=null,gl=null,program=null,buffers=[],savedFocus=null,player=null,audioTracks=[],sessionId=0,recordCanvas=null,recordCtx=null;
const stage=[['I · THE FIRST MARK','Before anyone named it'],['II · DEEP TIME','Stone remembers'],['III · THE LIVING LAND','Roots find the fractures'],['IV · PASSAGE','Paths become places'],['V · WHAT WE LEAVE','A world becomes a home']];
function rand(s){return()=>{s=Math.imul(s^s>>>15,1|s);s^=s+Math.imul(s^s>>>7,61|s);return((s^s>>>14)>>>0)/4294967296}}
let atlasField,atlasTexture;
function seedGeology(){atlasField=AtlasStudio.model()}
function surface(lon,lat){return atlasField.sample(lon,lat)}
// Deliberate pauses, close studies, and a final return to the whole globe.
const cameraKeys=[{t:0,z:3.55,a:.22,x:0,y:0},{t:8,z:2.85,a:.35,x:0,y:.08},{t:19,z:1.48,a:.62,x:0,y:.39},{t:27,z:1.58,a:.08,x:.12,y:-.08},{t:37,z:1.50,a:.58,x:-.04,y:-.23},{t:44,z:2.75,a:.85,x:0,y:0},{t:55,z:1.40,a:.70,x:0,y:-.15},{t:64,z:3.55,a:.95,x:0,y:0}];
function cameraAt(t){let k=0;while(k<cameraKeys.length-2&&t>cameraKeys[k+1].t)k++;const a=cameraKeys[k],b=cameraKeys[k+1],f=Math.max(0,Math.min(1,(t-a.t)/(b.t-a.t))),u=f*f*(3-2*f);return Object.fromEntries(['z','a','x','y'].map(key=>[key,a[key]+(b[key]-a[key])*u]))}
function v(lon,lat,r=1){return[Math.cos(lat)*Math.sin(lon)*r,Math.sin(lat)*r,Math.cos(lat)*Math.cos(lon)*r]}
function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function norm(a){let n=Math.hypot(...a)||1;return a.map(x=>x/n)}
function build(){seedGeology();let vertices=[];const colors={ice:[.70,.76,.73],mountain:[.73,.65,.49],forest:[.55,.62,.44],plains:[.80,.71,.47],canyon:[.72,.49,.34]};
function vert(base,offset,normal,color,birth,kind,uv=[0,0]){vertices.push(...base,...offset,...normal,...color,birth,kind,...uv)}
const nx=320,ny=192,grid=[];for(let b=0;b<=ny;b++)for(let a=0;a<=nx;a++){let lon=a/nx*TAU-Math.PI,lat=b/ny*Math.PI-Math.PI/2,p=v(lon,lat),s=surface(lon,lat);let shade=.92+.08*Math.sin(lon*100+lat*89);let color=s.land?colors[s.biome].map(x=>x*shade):[.80,.78,.65];let east=[Math.cos(lon),0,-Math.sin(lon)],north=cross(p,east),dx=(surface(lon+.002,lat).h-s.h)/.002/Math.max(.15,Math.cos(lat)),dy=(surface(lon,lat+.002).h-s.h)/.002;let normal=s.land?norm(p.map((n,i)=>n-east[i]*dx-north[i]*dy)):p;grid.push({p,s,color,normal,tex:[lon/TAU+.5,.5-lat/Math.PI]});}for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const n=nx+1,corners=[grid[j*n+i],grid[j*n+i+1],grid[(j+1)*n+i+1],grid[(j+1)*n+i]];for(let k of [0,1,2,0,2,3]){let q=corners[k];vert(q.p,q.p.map(x=>x*q.s.h),q.normal,q.color,.08,q.s.land?0:1,q.tex)}}
function object(lon,lat,h,radius,color,birth,type){h*=type==='tree'?.008:.006;radius*=type==='tree'?.10:.075;let s=surface(lon,lat),up=v(lon,lat),east=[Math.cos(lon),0,-Math.sin(lon)],north=cross(up,east),base=up.map(x=>x*(1+s.h));let world=([x,y,z])=>east.map((e,i)=>e*x+north[i]*z+up[i]*y);function tri(a,b,c){let na=norm(cross(b.map((x,i)=>x-a[i]),c.map((x,i)=>x-a[i])));let normal=world(na);for(let p of [a,b,c])vert(base,world(p),normal,color,birth,type==='city'?2:3,[p[0]/radius,p[1]/h])}
if(type==='tree'){let rng=rand(Math.abs(Math.floor(lon*91237+lat*71931))),form=Math.floor(rng()*3),sides=5+Math.floor(rng()*4),lean=(rng()-.5)*radius*.65;const rings=form===0?[[0,.2],[.18,.25],[.2,1],[.48,.18],[.5,.8],[.73,.12],[.75,.5],[1,0]]:form===1?[[0,.15],[.22,.17],[.32,.7],[.55,1],[.78,.75],[1,0]]:[[0,.18],[.15,.4],[.45,.55],[.8,.35],[1,0]];let ring=([y,w])=>Array.from({length:sides},(_,k)=>{let a=k/sides*TAU,r=radius*w*(.85+rng()*.3);return[Math.cos(a)*r+lean*y,y*h,Math.sin(a)*r]});let prev=ring(rings[0]);for(let j=1;j<rings.length;j++){let next=ring(rings[j]);for(let k=0;k<sides;k++){let n=(k+1)%sides;tri(prev[k],next[k],next[n]);tri(prev[k],next[n],prev[n])}prev=next}}
else if(type==='spire'){let n=4;for(let k=0;k<n;k++){let a=k/n*TAU,b=(k+1)/n*TAU;tri([Math.cos(a)*radius,0,Math.sin(a)*radius],[0,h,0],[Math.cos(b)*radius,0,Math.sin(b)*radius])} }else{let rng=rand(Math.abs(Math.floor(lon*36191+lat*97319))),tiers=2+Math.floor(rng()*3),depth=.7+rng()*.7,taper=.12+rng()*.42,twist=(rng()-.5)*.14;let outline=[[-.7,-1],[.7,-1],[1,-.7],[1,.7],[.7,1],[-.7,1],[-1,.7],[-1,-.7]];const ring=(y,w)=>outline.map(([x,z])=>[x*radius*w+twist*y*radius,y*h,z*radius*w*depth]);let prev=ring(0,1);for(let j=1;j<=tiers;j++){let next=ring(j/tiers,1-taper*j/tiers);for(let k=0;k<8;k++){let n=(k+1)%8;tri(prev[k],next[k],next[n]);tri(prev[k],next[n],prev[n])}prev=next}for(let k=1;k<7;k++)tri(prev[0],prev[k],prev[k+1]);}}

let r=rand(typeof seed!=='undefined'?seed:527193);for(let i=0;i<3300;i++){let lon=r()*TAU-Math.PI,lat=(r()-.5)*2.5,s=surface(lon,lat);if(!s.land||s.biome!=='forest'||s.h>.055)continue;object(lon,lat,.014+r()*.023,.005+r()*.004,[.35+r()*.12,.44+r()*.13,.28],.34+r()*.13,'tree')}
const cities=[[-.7,-.2],[-.12,-.34],[-.85,.5],[.25,.27],[1.94,.22],[-2.1,-.3]];for(let [lon,lat] of cities){for(let i=0;i<70;i++){let gx=(i%10-4.5)*.021,gy=(Math.floor(i/10)-3)*.022,l=lon+gx,t=lat+gy,s=surface(l,t);if(!s.land)continue;let central=Math.exp(-(gx*gx+gy*gy)*220);let h=.012+r()*.035+central*.065;object(l,t,h,.006+r()*.002,[.61+r()*.15,.56+r()*.12,.44+r()*.12],.68+r()*.22,'city');if(i%17===0)object(l,t,h+.025,.003,[.75,.67,.45],.89,'spire')}}
return new Float32Array(vertices)}
function init(canvas){gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});if(!gl)throw Error('WebGL unavailable');const vs=`precision mediump float;attribute vec3 base;attribute vec3 offset;attribute vec3 normal;attribute vec3 color;attribute float birth;attribute float kind;attribute vec2 uv;uniform float progress;uniform float angle;uniform float aspect;uniform float cameraZ;uniform float reliefGain;uniform vec2 focus;uniform vec2 objects;varying vec3 col;varying vec3 nor;varying vec3 pos;varying vec3 paperPos;varying float typ;varying vec2 tex;vec3 rot(vec3 p){float c=cos(angle),s=sin(angle);vec3 q=vec3(c*p.x+s*p.z,p.y,-s*p.x+c*p.z);float t=.16;return vec3(cos(t)*q.x-sin(t)*q.y,sin(t)*q.x+cos(t)*q.y,q.z);}void main(){float growth=smoothstep(birth,birth+.12,progress);vec3 model=base+offset*growth*reliefGain;if(kind>1.5){float show=kind<2.5?objects.y:objects.x;float nearDetail=1.-smoothstep(1.65,2.65,cameraZ);model=normalize(base)*(1.+(length(base)-1.)*reliefGain)+offset*growth*nearDetail;if(progress<birth||show<.5)model=normalize(base)*.99;}vec3 p=rot(model);vec3 n=rot(normal);float z=cameraZ-p.z;gl_Position=vec4((p.x-focus.x)*2.4/aspect,(p.y-focus.y)*2.4,(z-.35)*.72,z);col=color;nor=n;pos=p;paperPos=model;typ=kind;tex=uv;}`;
const derivatives=gl.getExtension('OES_standard_derivatives');
const fs=(derivatives?'#extension GL_OES_standard_derivatives : enable\n':'')+`precision mediump float;varying vec3 col;varying vec3 nor;varying vec3 pos;varying vec3 paperPos;varying float typ;varying vec2 tex;uniform sampler2D atlas;uniform float progress;uniform float cameraZ;uniform vec2 layers;uniform float paletteMode;vec3 elevationColor(float e){if(e<.33)return mix(vec3(.65,.70,.53),vec3(.81,.79,.58),smoothstep(.2,.33,e));if(e<.50)return mix(vec3(.81,.79,.58),vec3(.77,.64,.44),smoothstep(.33,.50,e));if(e<.70)return mix(vec3(.77,.64,.44),vec3(.65,.48,.37),smoothstep(.50,.70,e));return mix(vec3(.65,.48,.37),vec3(.94,.90,.78),smoothstep(.70,.95,e));}void main(){vec3 ink=vec3(.24,.19,.13),paper=vec3(.90,.85,.73);if(paletteMode>.5&&paletteMode<1.5){paper=vec3(.94,.93,.86);ink=vec3(.21,.25,.25);}if(paletteMode>1.5){paper=vec3(.13,.23,.29);ink=vec3(.79,.78,.64);}vec3 c=paper;float light=max(0.,dot(normalize(nor),normalize(vec3(-.6,.8,1.2))));if(typ<1.5){vec4 d=texture2D(atlas,tex);float e=d.r;float land=smoothstep(.195,.207,e);vec3 landColor=elevationColor(e);if(paletteMode>1.5)landColor=mix(paper,landColor,.45);float shaded=.67+d.g*.33;landColor*=shaded;float band=e*34.;float width=`+(derivatives?'max(.012,fwidth(band)*.72)':'.07')+`;float contour=1.-smoothstep(width,width*2.,abs(fract(band)-.5));landColor=mix(landColor,ink,contour*.38*layers.x);float slopeHatch=(1.-d.g)*(1.-smoothstep(.04,.12,abs(fract((tex.x+tex.y)*1100.)-.5)));landColor=mix(landColor,ink,slopeHatch*.22);c=mix(paper,landColor,land*smoothstep(.05,.22,progress));float coast=(1.-smoothstep(.001,.009,abs(e-.2)))*smoothstep(.015,.15,progress);c=mix(c,ink,coast*.78);float river=smoothstep(.30,.64,d.b)*land*layers.y*smoothstep(.32,.5,progress);c=mix(c,vec3(.22,.39,.43),river*.85);float graticule=(1.-smoothstep(.005,.018,abs(fract(tex.x*24.)-.5)))+(1.-smoothstep(.005,.018,abs(fract(tex.y*12.)-.5)));c=mix(c,ink,min(.1,graticule*.075)*(1.-land));}else{c=mix(paper,col,.6)*(.70+light*.3);if(typ<2.5){float windows=step(.48,fract(tex.x*3.))*step(.48,fract(tex.y*15.));c=mix(c,ink,windows*.62);}}float grain=fract(sin(dot(paperPos,vec3(12.98,78.23,39.42)))*4375.8);c+=(grain-.5)*.02;float rim=abs(dot(normalize(pos),normalize(vec3(0.,0.,cameraZ)-pos)));c*=.90+rim*.10;gl_FragColor=vec4(c,1.);}`;
function compile(type,s){let sh=gl.createShader(type);gl.shaderSource(sh,s);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh}program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vs));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Globe shader: '+gl.getProgramInfoLog(program));gl.useProgram(program);let data=build(),b=gl.createBuffer();buffers=[b];gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);let at=0;for(let [name,size]of [['base',3],['offset',3],['normal',3],['color',3],['birth',1],['kind',1],['uv',2]]){let loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,64,at*4);at+=size}atlasTexture=gl.createTexture();gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,atlasTexture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,atlasField.width,atlasField.height,0,gl.RGBA,gl.UNSIGNED_BYTE,atlasField.texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.uniform1i(gl.getUniformLocation(program,'atlas'),0);gl.enable(gl.DEPTH_TEST);return data.length/16}
function notice(message){const n=$('globe-notice');if(n)n.textContent=message;}
function release(){cancelAnimationFrame(raf);if(rec?.state==='recording')rec.stop();stream?.getTracks().forEach(t=>t.stop());stream=null;rec=null;recordCanvas=null;recordCtx=null;if(player){player.pause();player.removeAttribute('src');player.load();player=null}if(ac){ac.close().catch(()=>{});ac=null}if(gl){if(atlasTexture)gl.deleteTexture(atlasTexture);atlasTexture=null;buffers.forEach(b=>gl.deleteBuffer(b));if(program)gl.deleteProgram(program);gl.getExtension('WEBGL_lose_context')?.loseContext();gl=null}buffers=[];program=null;}
function start(record=false){if(running)return;running=true;const session=++sessionId;savedFocus=document.activeElement;let wrap=document.createElement('div');wrap.id='globe-film';wrap.innerHTML='<canvas id="globe3d" width="1920" height="1080"></canvas><div class="globe-heading"><small id="globe-stage"></small><h2 id="globe-title">Preparing your world…</h2></div><div class="globe-audio"><audio id="globe-audio" controls preload="auto"></audio><p id="globe-notice" role="status"></p></div><div class="globe-footer"><span>AS THE STARS FALL · LOGICMOON</span><span id="globe-time"></span></div><button id="globe-close">End reveal</button><button id="globe-retry" hidden>Try again</button><div class="director"><div class="director-buttons"><button id="film-pause">Pause</button><button id="film-explore">Explore globe</button><button data-chapter="0">Ocean</button><button data-chapter="12">Ranges</button><button data-chapter="27">Valleys</button><button data-chapter="40">Life</button><button data-chapter="56">Cities</button></div><label for="film-seek">Film position</label><input id="film-seek" type="range" min="0" max="64" step="0.1" value="0"><small>Drag to orbit and scroll to zoom in Explore mode.</small></div><div class="globe-progress"><i id="globe-progress"></i></div>';document.body.append(wrap);$('globe-close').onclick=stop;$('globe-close').focus();$('globe-retry').onclick=()=>{stop();start(record)};
// Request playback during the click gesture, before mesh generation or any await.
player=$('globe-audio');player.src=new URL('stars-score.mp3',document.baseURI).href;player.volume=.8;const activePlayer=player;
if(record&&$('music').checked){try{ac=new(window.AudioContext||window.webkitAudioContext)();ac.resume().catch(()=>notice('Use the audio Play control to enable the soundtrack.'));const media=ac.createMediaElementSource(player);media.connect(ac.destination);const dest=ac.createMediaStreamDestination();media.connect(dest);audioTracks=dest.stream.getAudioTracks()}catch(e){audioTracks=[];notice('Audio capture is unavailable. The globe can still play.')}}else audioTracks=[];
player.addEventListener('error',()=>{if(session===sessionId)notice('The soundtrack could not load. The globe will continue; use Play to retry the sound.');});
if($('music').checked){const play=player.play();if(play)play.catch(()=>{if(session===sessionId)notice('Press Play in the audio controls to enable the soundtrack.');});}else notice('Music is off. Press Play below to listen.');
// Give the browser a chance to paint the player before building the 3D mesh.
raf=requestAnimationFrame(()=>{if(!running||session!==sessionId)return;try{const canvas=$('globe3d'),count=init(canvas);if(gl.getError()!==gl.NO_ERROR)throw Error('The graphics device could not prepare the globe.');
if(record){if(!canvas.captureStream||!window.MediaRecorder)throw Error('This browser does not support video recording. Use Build a 3D globe to play it.');recordCanvas=document.createElement('canvas');recordCanvas.width=1920;recordCanvas.height=1080;recordCtx=recordCanvas.getContext('2d');stream=recordCanvas.captureStream(30);audioTracks.forEach(t=>stream.addTrack(t));const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/mp4'].find(m=>MediaRecorder.isTypeSupported(m));rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:8000000}:undefined);let chunks=[],r=rec;r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onstop=()=>{if(!chunks.length)return;let blob=new Blob(chunks,{type:r.mimeType}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='inkbound-globe.'+(r.mimeType.includes('mp4')?'mp4':'webm');a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};rec.start(200)}
// Start the sequence independently of audio availability. Reset sound to the same origin.
try{activePlayer.currentTime=0}catch{}const startTime=performance.now();let playhead=0,previousTime=startTime,paused=false,manualCam=null,drag=null;
function seek(value){playhead=Math.max(0,Math.min(DURATION,value));try{activePlayer.currentTime=playhead}catch{}if(playhead>=DURATION){paused=true;activePlayer.pause()}previousTime=performance.now();}
$('film-pause').onclick=()=>{paused=!paused;$('film-pause').textContent=paused?'Play':'Pause';if(paused)activePlayer.pause();else if($('music').checked)activePlayer.play().catch(()=>notice('Press Play on the audio control to enable sound.'))};
$('film-explore').onclick=()=>{if(manualCam){manualCam=null;$('film-explore').textContent='Explore globe'}else{manualCam=cameraAt(playhead);paused=true;activePlayer.pause();$('film-pause').textContent='Play';$('film-explore').textContent='Follow film camera'}};
$('film-seek').oninput=e=>seek(Number(e.target.value));document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>seek(Number(b.dataset.chapter)));
canvas.onpointerdown=e=>{if(manualCam){drag={x:e.clientX,y:e.clientY,a:manualCam.a,fy:manualCam.y};canvas.setPointerCapture(e.pointerId)}};canvas.onpointermove=e=>{if(drag&&manualCam){manualCam.a=drag.a+(e.clientX-drag.x)*.005;manualCam.y=Math.max(-.7,Math.min(.7,drag.fy+(e.clientY-drag.y)*.002))}};canvas.onpointerup=canvas.onpointercancel=()=>{drag=null};canvas.onwheel=e=>{if(manualCam){e.preventDefault();manualCam.z=Math.max(1.20,Math.min(4.5,manualCam.z+e.deltaY*.0015))}};
if(record){document.querySelectorAll('.director button,.director input').forEach(b=>b.disabled=true)}
const uniforms=Object.fromEntries(['progress','angle','aspect','time','cameraZ','focus','reliefGain','objects','layers','paletteMode'].map(k=>[k,gl.getUniformLocation(program,k)]));
function frame(now){if(!running||session!==sessionId)return;try{if(!paused)playhead=Math.min(DURATION,playhead+Math.max(0,now-previousTime)/1000);previousTime=now;const t=playhead,p=t/DURATION;$('film-seek').value=t;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.85,.78,.64,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniform1f(uniforms.progress,p);gl.uniform1f(uniforms.reliefGain,Number($('relief-gain').value));gl.uniform2f(uniforms.objects,$('layer-forest').checked?1:0,$('layer-cities').checked?1:0);gl.uniform2f(uniforms.layers,$('layer-contours').checked?1:0,$('layer-rivers').checked?1:0);gl.uniform1f(uniforms.paletteMode,['parchment','ivory','night'].indexOf($('palette').value));const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,cam=reduced?{a:.35,z:3.4,x:0,y:0}:(manualCam||cameraAt(t));gl.uniform1f(uniforms.angle,cam.a);gl.uniform1f(uniforms.cameraZ,cam.z);gl.uniform2f(uniforms.focus,cam.x,cam.y);gl.uniform1f(uniforms.aspect,canvas.width/canvas.height);gl.uniform1f(uniforms.time,t);gl.drawArrays(gl.TRIANGLES,0,count);if(gl.isContextLost())throw Error('The graphics device stopped. Close other graphics-heavy tabs and try again.');let i=p<.08?0:p<.34?1:p<.62?2:p<.83?3:4;$('globe-stage').textContent=stage[i][0];$('globe-title').textContent=stage[i][1];if(recordCtx){recordCtx.drawImage(canvas,0,0,1920,1080);recordCtx.fillStyle='#efe3c6e6';recordCtx.fillRect(36,34,640,116);recordCtx.fillStyle='#58452c';recordCtx.font='16px sans-serif';recordCtx.fillText(stage[i][0],58,69);recordCtx.font='34px Georgia';recordCtx.fillText(stage[i][1],58,118);recordCtx.font='13px sans-serif';recordCtx.fillText('INKBOUND · AS THE STARS FALL / LOGICMOON',42,1040);}$('globe-time').textContent=Math.floor(t)+' / 64 SEC';$('globe-progress').style.width=p*100+'%';if(t>=DURATION&&!paused){paused=true;$('film-pause').textContent='Play';if(rec?.state==='recording')rec.stop();activePlayer.pause();notice('Reveal complete. Scrub back or explore the globe.');$('globe-retry').hidden=false;}raf=requestAnimationFrame(frame);}catch(e){fail(e)}}frame(startTime);
}catch(e){fail(e)}});
}
function fail(e){sessionId++;release();$('globe-title').textContent='The globe could not start';notice(e.message);$('globe-retry').hidden=false;$('status').textContent='Globe playback: '+e.message;}
function stop(){if(!running)return;running=false;sessionId++;release();$('globe-film')?.remove();savedFocus?.focus()}
document.addEventListener('keydown',e=>{if(e.key==='Escape')stop()});$('cinema').onclick=()=>start();$('record').onclick=()=>start(true);
})();
