/* Shared elevation model for the atlas and globe. UI edits never alter renderer data. */
(()=>{const $=id=>document.getElementById(id);let cached=null,key='',sheet=null,sheetKey='';
function settings(){return{rough:Number($('terrain-rugged').value),relief:Number($('relief-gain').value),view:$('atlas-view').value,contours:$('layer-contours').checked,rivers:$('layer-rivers').checked,forest:$('layer-forest').checked,cities:$('layer-cities').checked}}
function model(){let next=seed+'|'+kind+'|'+$('terrain-rugged').value;if(next!==key||!cached){cached=TerrainAtlas.create(seed,world.coasts,{rugged:$('terrain-rugged').value});key=next;sheet=null;$('terrain-summary').textContent=cached.stats.riverCells.toLocaleString()+' drainage cells · one shared atlas & globe'}return cached}
const mix=(a,b,t)=>a.map((x,i)=>x+(b[i]-x)*t);function color(h){if(h<33)return mix([166,178,135],[207,201,148],Math.max(0,(h-20)/13));if(h<50)return mix([207,201,148],[196,163,112],(h-33)/17);if(h<70)return mix([196,163,112],[166,122,94],(h-50)/20);return mix([166,122,94],[240,230,199],Math.min(1,(h-70)/25))}
function image(){let m=model(),k=key+JSON.stringify(settings())+$('palette').value;if(sheet&&sheetKey===k)return sheet;sheet=document.createElement('canvas');sheet.width=1600;sheet.height=1100;let c=sheet.getContext('2d'),im=c.createImageData(1600,1100),night=$('palette').value==='night',ivory=$('palette').value==='ivory',paper=night?[34,58,74]:ivory?[239,238,220]:[231,219,190],contours=$('layer-contours').checked,rivers=$('layer-rivers').checked;
for(let y=0;y<1100;y++)for(let x=0;x<1600;x++){let [mx,my]=m.mapPoint(x,y),ix=Math.floor(mx),iy=Math.floor(my),u=mx-ix,v=my-iy,i=iy*m.width+ix,a=(1-u)*(1-v),b=u*(1-v),d=(1-u)*v,e=u*v;let height=m.heights[i]*a+m.heights[i+1]*b+m.heights[i+m.width]*d+m.heights[i+m.width+1]*e,land=height>=20;let col=land?color(height):paper.slice(),shade=(m.texture[i*4+1]*a+m.texture[(i+1)*4+1]*b+m.texture[(i+m.width)*4+1]*d+m.texture[(i+m.width+1)*4+1]*e)/255;if(land){if(night)col=mix(paper,col,.45);col=col.map(z=>z*(.67+shade*.33));let band=height/3,frac=band-Math.floor(band),slope=Math.abs(m.heights[i+1]-m.heights[i])+Math.abs(m.heights[i+m.width]-m.heights[i]),lineWidth=Math.max(.028,Math.min(.19,slope*.038));if(contours&&Math.abs(frac-.5)<lineWidth)col=mix(col,night?[200,197,164]:[64,47,32],.37);let river=m.texture[i*4+2]/255;if(rivers&&river>.5)col=mix(col,[66,105,111],river*.80);}if(Math.abs(height-20)<.9)col=mix(col,[68,56,36],.55);let grain=((x*13+y*7)%17-8)*.16;let off=(y*1600+x)*4;for(let j=0;j<3;j++)im.data[off+j]=col[j]+grain;im.data[off+3]=255;}c.putImageData(im,0,0);sheetKey=k;return sheet}
function drawRelief(progress=1){if($('atlas-view').value!=='relief'||mode==='draw')return false;let c=ctx,m=model(),pic=image();c.setTransform(1,0,0,1,0,0);c.fillStyle=$('palette').value==='night'?'#223a4a':'#e7dbbe';c.fillRect(0,0,W,H);c.save();c.beginPath();c.rect(38,38,W-76,H-76);c.clip();c.translate(W/2+pan.x,H/2+pan.y);c.scale(zoom,zoom);c.translate(-W/2,-H/2);c.drawImage(pic,0,0);if($('labels').checked){for(let r of world.labels){c.fillStyle='#f0e4cbd9';c.fillRect(r.bounds.x-5,r.bounds.y-4,r.bounds.w+10,r.bounds.h+8);c.fillStyle='#473b28';c.font='16px Georgia';c.textAlign='center';c.fillText(r.name,r.x,r.y+2,r.w)}for(let f of features.filter(f=>f.type==='castle')){c.fillStyle='#473b28';c.beginPath();c.arc(f.x,f.y,3.5,0,Math.PI*2);c.fill();c.font='13px Georgia';c.textAlign='center';c.fillText(f.name,f.x,f.y+18,100)}}c.restore();c.strokeStyle='#79674d';c.strokeRect(22,22,W-44,H-44);compass();c.fillStyle='#514731';c.font='12px Georgia';c.textAlign='left';c.fillText('LOWLANDS',1110,1050);c.fillText('HIGHLANDS',1380,1050);for(let j=0;j<100;j++){c.fillStyle='rgb('+color(20+j*.7).join(',')+')';c.fillRect(1110+j*3,1017,3,12)}return true}
function refresh(){sheet=null;draw();$('relief-value').textContent=Math.round(Number($('relief-gain').value)*100)+'%';}
function restore(s){if(!s)return;for(let [k,id]of [['rough','terrain-rugged'],['relief','relief-gain'],['view','atlas-view']])if(s[k]!==undefined)$(id).value=s[k];for(let [k,id]of [['contours','layer-contours'],['rivers','layer-rivers'],['forest','layer-forest'],['cities','layer-cities']])if(typeof s[k]==='boolean')$(id).checked=s[k];cached=null;sheet=null}
window.AtlasStudio={model,draw:drawRelief,settings,restore};['terrain-rugged','relief-gain','atlas-view','layer-contours','layer-rivers','layer-forest','layer-cities'].forEach(id=>$(id).addEventListener('change',refresh));document.querySelectorAll('[data-terrain-preset]').forEach(b=>b.onclick=()=>{$('terrain-rugged').value=b.dataset.terrainPreset;refresh()});$('atlas-view').value='relief';refresh();})();
